In [1]:
import MTools
import numpy as np



In [2]:
mt = MTools.MTools()

In [3]:

m1 = 4
n1 = 4
m2 = n1
n2 = 4

m3 = m1
n3 = n2

In [4]:
mat1 = np.random.rand(m1, n1)
mat2 = np.random.rand(m2, n2)
mat3 = np.random.rand(m3, n3)




mt.set_m1(mat1)

mt.set_m2(mat2)
mt.set_m3(mat3)



In [5]:
%%time
m3true = np.matmul(mat1, mat2)

CPU times: user 12 µs, sys: 11 µs, total: 23 µs
Wall time: 24.8 µs


In [6]:
%%time
mt.mm12()
m3gpu = mt.get_m3()

4 4
CPU times: user 96 µs, sys: 86 µs, total: 182 µs
Wall time: 177 µs


In [7]:
np.abs(m3true - m3gpu).max()

2.220446049250313e-16

In [8]:
m1sy = mat1.copy() 

for i in range(m1):
    for j in range(i+1, m1):
        m1sy[i][j] = m1sy[j][i]

In [9]:
mt.set_m1(m1sy)

In [10]:
mt.m1_eigen()

In [11]:
W1=mt.get_W1()

In [12]:
W1

array([-0.736416  ,  0.36440068,  0.90985076,  2.07459823])

In [18]:
mt.get_m1()

array([[ 0.69271544, -0.45690046, -0.3258788 , -0.45297935],
       [-0.5962131 , -0.45243564,  0.23107434, -0.62164024],
       [ 0.27559535,  0.63399935,  0.4653144 , -0.55278797],
       [-0.29786316,  0.42963797, -0.78986718, -0.32062218]])

In [19]:
np.linalg.eig(m1sy)

(array([-0.736416  ,  2.07459823,  0.36440068,  0.90985076]),
 array([[ 0.69271544, -0.45297935, -0.45690046,  0.3258788 ],
        [-0.5962131 , -0.62164024, -0.45243564, -0.23107434],
        [ 0.27559535, -0.55278797,  0.63399935, -0.4653144 ],
        [-0.29786316, -0.32062218,  0.42963797,  0.78986718]]))