In [1]:
import MTools
import numpy as np



In [2]:
mt = MTools.MTools(use_svd=True)

# Matrix MM

In [3]:

m1 = 6
n1 = 4
m2 = n1
n2 = 4
m3 = m1
n3 = n2



In [4]:
mat1 = np.random.rand(m1, n1)
mat2 = np.random.rand(m2, n2)
mat3 = np.random.rand(m3, n3)

mt.set_m1(mat1)

mt.set_m2(mat2)
mt.set_m3(mat3)


In [5]:
m3true = np.matmul(mat1, mat2)

In [6]:
mt.mm12()
m3gpu = mt.get_m3()

In [7]:
np.abs(m3true - m3gpu).max()

4.440892098500626e-16

# Matrix eigen

In [8]:
m1 = 4
n1 = 4


mat1 = np.random.rand(m1, n1)



m1sy = mat1.copy() 

for i in range(m1):
    for j in range(i+1, m1):
        m1sy[i][j] = m1sy[j][i]
        
mt.set_m1(m1sy)

In [9]:
mt.m1_eigen()

In [10]:
# Eigen values
W1=mt.get_W1()
print(W1)

[-0.72854772 -0.22194983  0.77054468  2.09574054]


In [11]:
# Eigen vectors
v1 = mt.get_m1()
print(v1)

[[-0.33392797  0.04945645 -0.81638355  0.46857665]
 [-0.60886559 -0.17562469  0.55040866  0.54358897]
 [ 0.65854474 -0.50799064  0.01836005  0.55491192]
 [ 0.28998901  0.84181681  0.17387099  0.42073711]]


In [12]:
# True value
np.linalg.eig(m1sy)

(array([ 2.09574054,  0.77054468, -0.72854772, -0.22194983]),
 array([[ 0.46857665,  0.81638355,  0.33392797,  0.04945645],
        [ 0.54358897, -0.55040866,  0.60886559, -0.17562469],
        [ 0.55491192, -0.01836005, -0.65854474, -0.50799064],
        [ 0.42073711, -0.17387099, -0.28998901,  0.84181681]]))

# Matrix SVD

In [13]:
m1 = 6
n1 = 4

mat1 = np.random.rand(m1, n1)

mat1_bak = mat1.copy()


mt.set_m1(mat1)



In [14]:
mt.m1_svd()

In [15]:
S1 = mt.get_S1()
VT1 = mt.get_VT1()
U1 = mt.get_U1()

In [16]:
S1, VT1, U1

(array([2.58523424, 0.83548504, 0.58800774, 0.3471599 ]),
 array([[-0.47957215,  0.        ,  0.12706485, -0.72794958],
        [ 0.28225888,  0.        , -0.1287462 ,  0.28612451],
        [-0.1575155 , -0.36114162,  0.        ,  0.4389906 ],
        [-0.81579982, -0.91479816,  0.        ,  0.44216448]]),
 array([[-0.53835004,  0.31515105, -0.1415671 , -0.36622513, -0.67555308,
         -0.01802749],
        [-0.33803045,  0.19933835,  0.50220054,  0.25670621,  0.13700805,
         -0.71352994],
        [-0.29182874, -0.37310209, -0.1929151 ,  0.78483943, -0.32967006,
          0.11730003],
        [-0.3105351 , -0.45245378, -0.58201158, -0.27573428,  0.31922647,
         -0.42682681],
        [-0.47130206,  0.50359424, -0.21113244,  0.18348597,  0.54498597,
          0.38602266],
        [-0.43839817, -0.51324194,  0.55427678, -0.27260162,  0.1313744 ,
          0.38157061]]))

In [17]:
np.linalg.svd(mat1_bak)

(array([[-0.53835004,  0.31515105, -0.1415671 , -0.36622513, -0.67555308,
         -0.01802749],
        [-0.33803045,  0.19933835,  0.50220054,  0.25670621,  0.13700805,
         -0.71352994],
        [-0.29182874, -0.37310209, -0.1929151 ,  0.78483943, -0.32967006,
          0.11730003],
        [-0.3105351 , -0.45245378, -0.58201158, -0.27573428,  0.31922647,
         -0.42682681],
        [-0.47130206,  0.50359424, -0.21113244,  0.18348597,  0.54498597,
          0.38602266],
        [-0.43839817, -0.51324194,  0.55427678, -0.27260162,  0.1313744 ,
          0.38157061]]),
 array([2.58523424, 0.83548504, 0.58800774, 0.3471599 ]),
 array([[-0.47957215, -0.36114162, -0.72794958, -0.33117471],
        [ 0.28225888, -0.91479816,  0.28612451, -0.04008766],
        [-0.1575155 ,  0.12706485,  0.4389906 , -0.87540313],
        [-0.81579982, -0.1287462 ,  0.44216448,  0.3498366 ]]))